name: blink
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  get_it: ^7.6.7

  go_router: ^13.2.0

  flutter_screenutil: ^5.9.3

  shared_preferences: ^2.3.2

  cached_network_image: ^3.4.1

  image_picker: ^1.1.2

  camera: ^0.11.0+2

  rxdart: ^0.28.0

  provider: ^6.1.2

  intl: ^0.20.1

  path_provider: ^2.1.5

  url_launcher: ^6.3.1

  flutter_local_notifications: ^18.0.1

  permission_handler: ^11.3.1

  cloud_functions: ^5.2.0
  #firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.1.5

  video_player: ^2.9.2

  ffmpeg_kit_flutter: ^6.0.3
  firebase_dynamic_links: ^6.0.11
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/point/tree.png
    - assets/images/point/fruit.png
