// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4REIguWKEnefXgmLHX_25D8Dk_HIMSG4',
    appId: '1:623164352186:web:b4c60c2976ca7d29b88483',
    messagingSenderId: '623164352186',
    projectId: 'blink-app-8d6ca',
    authDomain: 'blink-app-8d6ca.firebaseapp.com',
    storageBucket: 'blink-app-8d6ca.firebasestorage.app',
    measurementId: 'G-VEYNPTH1M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN_yjmPfbw1D4hWBFvY2KPckfsSUi2rDk',
    appId: '1:623164352186:android:9c63de8750e70907b88483',
    messagingSenderId: '623164352186',
    projectId: 'blink-app-8d6ca',
    storageBucket: 'blink-app-8d6ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvobCdeJrNzPfQ9yOki7FpPEFo7cHEVDU',
    appId: '1:623164352186:ios:bedae90a9c49ab99b88483',
    messagingSenderId: '623164352186',
    projectId: 'blink-app-8d6ca',
    storageBucket: 'blink-app-8d6ca.firebasestorage.app',
    iosBundleId: 'com.blink.blink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvobCdeJrNzPfQ9yOki7FpPEFo7cHEVDU',
    appId: '1:623164352186:ios:bedae90a9c49ab99b88483',
    messagingSenderId: '623164352186',
    projectId: 'blink-app-8d6ca',
    storageBucket: 'blink-app-8d6ca.firebasestorage.app',
    iosBundleId: 'com.blink.blink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4REIguWKEnefXgmLHX_25D8Dk_HIMSG4',
    appId: '1:623164352186:web:4ac770320255cbb2b88483',
    messagingSenderId: '623164352186',
    projectId: 'blink-app-8d6ca',
    authDomain: 'blink-app-8d6ca.firebaseapp.com',
    storageBucket: 'blink-app-8d6ca.firebasestorage.app',
    measurementId: 'G-VT18WCQPJW',
  );
}
